# Site settings
title: 全球最大的B2B商务社交平台，找买家、收询盘、交朋友 - 外贸公社
email: erickohx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  全球最大的B2B商务社交平台，找买家、收询盘、交朋友 - 外贸公社
#baseurl: "landing-page" # the subpath of your site, e.g. /blog/
url: "http://www.ierickoh.com" # the base hostname & protocol for your site
twitter_username: _iEricKoh
github_username:  iEricKoh

# Build settings
markdown: kramdown

include: [".nojekyll"]
exclude: ["bower_components", "bower.json", "node_modules", "package.json", "Gruntfile.coffee"]
